---
- name: Disable roger
  shell: roger update --all_alarms false $(hostname)
  become: true

- name: Disable nagios
  nagios:
    action: disable_alerts
    service: all
    host: '{{ inventory_hostname }}'
  delegate_to: "{{ groups[env+'-monitor'][0] }}"
  become: true

- name: Disable lemon
  shell: /sbin/service lemon-agent stop && /sbin/service lemon-forwarder stop
  become: true
