---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - inspire-qa-logs-data1.cern.ch
    - inspire-qa-logs-data2.cern.ch
    - inspire-qa-logs-data3.cern.ch
    - inspire-qa-logs-master1.cern.ch
    - inspire-qa-logs-client1.cern.ch
    - inspire-qa-logs-client2.cern.ch
  port: 443
  url_prefix:
  use_ssl: True
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: True
  http_auth: ${APPMETRICS_ELASTICSEARCH_AUTH}
  timeout: 600
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
