---
- import_tasks: close_shells.yml

- import_tasks: disable_alarms.yml

- import_tasks: stop_celery.yml

- import_tasks: update_python_code_and_venv.yml

- import_tasks: copy_config_file.yml

- import_tasks: start_celery.yml

- import_tasks: enable_alarms.yml
