---
- hosts: prod
  tasks:
    - name: git log
      shell: git log -10
      args:
        chdir: /opt/inspire/src/inspire
      tags:
        - git-log-prod
      register: result
    - debug:
        var: result
        verbosity: 0
      tags:
        - git-log-prod
